language: javascript
javascript:
  - 1.8.5
script:
  - phantomjs t/testTool.js
  - phantomjs t/test_validator.js

#safelist( makes Travis run on gh-pages branch )
branches:
  only:
    - master
    - gh-pages
    - /^experimental.*$/

